// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/protocol/debug.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerType int32

const (
	ServerType_PROD ServerType = 0
	ServerType_DEV  ServerType = 1
)

var ServerType_name = map[int32]string{
	0: "PROD",
	1: "DEV",
}

var ServerType_value = map[string]int32{
	"PROD": 0,
	"DEV":  1,
}

func (x ServerType) String() string {
	return proto.EnumName(ServerType_name, int32(x))
}

func (ServerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7d558baaf08f173c, []int{0}
}

type ServerInfo struct {
	// Whether this is a production or development server.
	Type ServerType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.ServerType" json:"type,omitempty"`
	// Identity of server.
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Port the server is running on.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Established connections.
	Connections          uint32   `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d558baaf08f173c, []int{0}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetType() ServerType {
	if m != nil {
		return m.Type
	}
	return ServerType_PROD
}

func (m *ServerInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ServerInfo) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServerInfo) GetConnections() uint32 {
	if m != nil {
		return m.Connections
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d558baaf08f173c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protocol.ServerType", ServerType_name, ServerType_value)
	proto.RegisterType((*ServerInfo)(nil), "protocol.ServerInfo")
	proto.RegisterType((*Empty)(nil), "protocol.Empty")
}

func init() {
	proto.RegisterFile("internal/protocol/debug.proto", fileDescriptor_7d558baaf08f173c)
}

var fileDescriptor_7d558baaf08f173c = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcd, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x4f, 0x49,
	0x4d, 0x2a, 0x4d, 0xd7, 0x03, 0x73, 0x85, 0x38, 0x60, 0xa2, 0x4a, 0x35, 0x5c, 0x5c, 0xc1, 0xa9,
	0x45, 0x65, 0xa9, 0x45, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0x1a, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x22, 0x7a, 0x30, 0x65, 0x7a, 0x10, 0x35, 0x21, 0x95,
	0x05, 0xa9, 0x41, 0x60, 0x15, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a,
	0xbc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0xf9, 0x45, 0x25, 0x12, 0xcc, 0x60,
	0x11, 0x30, 0x5b, 0x48, 0x81, 0x8b, 0x3b, 0x39, 0x3f, 0x2f, 0x2f, 0x35, 0xb9, 0x24, 0x33, 0x3f,
	0xaf, 0x58, 0x82, 0x05, 0x2c, 0x85, 0x2c, 0xa4, 0xc4, 0xce, 0xc5, 0xea, 0x9a, 0x5b, 0x50, 0x52,
	0xa9, 0x25, 0x0f, 0x73, 0x06, 0xc8, 0x0a, 0x21, 0x0e, 0x2e, 0x96, 0x80, 0x20, 0x7f, 0x17, 0x01,
	0x06, 0x21, 0x76, 0x2e, 0x66, 0x17, 0xd7, 0x30, 0x01, 0x46, 0x23, 0x7b, 0x2e, 0x56, 0x17, 0x90,
	0x07, 0x84, 0xcc, 0xb8, 0xb8, 0x03, 0x4b, 0x53, 0x8b, 0x2a, 0x21, 0xca, 0x85, 0xf8, 0x11, 0x6e,
	0x04, 0x9b, 0x24, 0x85, 0xe1, 0x68, 0x90, 0xc7, 0x94, 0x18, 0x9c, 0x64, 0xa2, 0xa4, 0xf4, 0xf4,
	0xd3, 0x52, 0xf3, 0x8a, 0x32, 0x8b, 0xf4, 0x31, 0x02, 0x27, 0x89, 0x0d, 0xcc, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x92, 0x2a, 0x9f, 0x38, 0x01, 0x00, 0x00,
}
