// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: internal/protocol/protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerType int32

const (
	ServerType_PROD ServerType = 0
	ServerType_DEV  ServerType = 1
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "PROD",
		1: "DEV",
	}
	ServerType_value = map[string]int32{
		"PROD": 0,
		"DEV":  1,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_protocol_proto_enumTypes[0].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_internal_protocol_protocol_proto_enumTypes[0]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

type ServerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether this is a production or development server.
	Type ServerType `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.ServerType" json:"type,omitempty"`
	// Identity of server.
	Id int32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// Port the server is running on.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// Established connections.
	Connections   int32 `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_internal_protocol_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetType() ServerType {
	if x != nil {
		return x.Type
	}
	return ServerType_PROD
}

func (x *ServerInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfo) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

var File_internal_protocol_protocol_proto protoreflect.FileDescriptor

const file_internal_protocol_protocol_proto_rawDesc = "" +
	"\n" +
	" internal/protocol/protocol.proto\x12\bprotocol\x1a\x1bgoogle/protobuf/empty.proto\"|\n" +
	"\n" +
	"ServerInfo\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.protocol.ServerTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12 \n" +
	"\vconnections\x18\x04 \x01(\x05R\vconnections*\x1f\n" +
	"\n" +
	"ServerType\x12\b\n" +
	"\x04PROD\x10\x00\x12\a\n" +
	"\x03DEV\x10\x012F\n" +
	"\x05Debug\x12=\n" +
	"\vQueryServer\x12\x16.google.protobuf.Empty\x1a\x14.protocol.ServerInfo\"\x00B\x1cZ\x1a./fenrir/internal/protocolb\x06proto3"

var (
	file_internal_protocol_protocol_proto_rawDescOnce sync.Once
	file_internal_protocol_protocol_proto_rawDescData []byte
)

func file_internal_protocol_protocol_proto_rawDescGZIP() []byte {
	file_internal_protocol_protocol_proto_rawDescOnce.Do(func() {
		file_internal_protocol_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_protocol_proto_rawDesc), len(file_internal_protocol_protocol_proto_rawDesc)))
	})
	return file_internal_protocol_protocol_proto_rawDescData
}

var file_internal_protocol_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_protocol_proto_goTypes = []any{
	(ServerType)(0),       // 0: protocol.ServerType
	(*ServerInfo)(nil),    // 1: protocol.ServerInfo
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_internal_protocol_protocol_proto_depIdxs = []int32{
	0, // 0: protocol.ServerInfo.type:type_name -> protocol.ServerType
	2, // 1: protocol.Debug.QueryServer:input_type -> google.protobuf.Empty
	1, // 2: protocol.Debug.QueryServer:output_type -> protocol.ServerInfo
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protocol_protocol_proto_init() }
func file_internal_protocol_protocol_proto_init() {
	if File_internal_protocol_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_protocol_proto_rawDesc), len(file_internal_protocol_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_protocol_proto_goTypes,
		DependencyIndexes: file_internal_protocol_protocol_proto_depIdxs,
		EnumInfos:         file_internal_protocol_protocol_proto_enumTypes,
		MessageInfos:      file_internal_protocol_protocol_proto_msgTypes,
	}.Build()
	File_internal_protocol_protocol_proto = out.File
	file_internal_protocol_protocol_proto_goTypes = nil
	file_internal_protocol_protocol_proto_depIdxs = nil
}
